### ISSUE TITLE
most assets return a 404 even though the site is working and they are there.

### ISSUE THREAD

**Issue by HarrisRobin** [koolth/generator-bourbon-neat#5]
https://www.dropbox.com/s/80rob4nytrdcp6l/Screenshot%202014-12-03%2022.32.47.png?dl=0

I used this generator for the first time today and everything seemed to work perfectly until it came time to deploy. Most of my assets give me a 404 on development. When I do grunt build (after applying the fix in the issue concerning ugflify) my scripts are not minified and moved over to the scripts folder (however there are no 404s on the dist version). 

Anyone ran into this problem ? Could use some pointers as i have to deploy this tomorrow. Thanks !

**Comment by drpuff** [comment]
v1.0.0 coming out very soon (in GitHub today and npm tomorrow...hopefully).

Try it again!
